### ISSUE TITLE
Error loading script: composable_lora_script.py

### ISSUE THREAD

**Issue by banMo88** [a2569875/stable-diffusion-webui-composable-lora#1]
Error loading script: composable_lora_script.py
Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/notebooks/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-composable-lora/scripts/composable_lora_script.py", line 7, in <module>
    import composable_lora
  File "/notebooks/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-composable-lora/composable_lora.py", line 4, in <module>
    import composable_lora_step
  File "/notebooks/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-composable-lora/composable_lora_step.py", line 194, in <module>
    class LoRA_StartEnd_Controller(LoRA_Controller_Base):
  File "/notebooks/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-composable-lora/composable_lora_step.py", line 195, in LoRA_StartEnd_Controller
    def __init__(self, name : str, weight : float, start : float | int, end : float | int):
TypeError: unsupported operand type(s) for |: 'type' and 'type'

don't know why.

**Comment by a2569875** [comment]
@banMo88 The minimum requirement for this extension is Python 3.10, please check it out, thanks.
