### ISSUE TITLE
不起作用

### ISSUE THREAD

**Issue by alphaply** [a2569875/stable-diffusion-webui-composable-lora#13]
请问文档中的测试是如何做到的，我进行绘制时应该没有成功，没有之前的效果好，终端有以下错误
---
2023-06-29 13:05:54,419 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
*** Error running process: E:\ai\sdwebui\sdwebui\stable-diffusion-webui\extensions\stable-diffusion-webui-composable-lora\scripts\composable_lora_script.py
    Traceback (most recent call last):
      File "E:\ai\sdwebui\sdwebui\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: ComposableLoraScript.process() missing 7 required positional arguments: 'enabled', 'opt_composable_with_step', 'opt_uc_text_model_encoder', 'opt_uc_diffusion_model', 'opt_plot_lora_weight', 'opt_single_no_uc', and 'opt_hires_step_as_global'

---
*** Error running process: E:\ai\sdwebui\sdwebui\stable-diffusion-webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py
    Traceback (most recent call last):
      File "E:\ai\sdwebui\sdwebui\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "E:\ai\sdwebui\sdwebui\stable-diffusion-webui\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py", line 557, in process
        enabled, raw_divisions, raw_positions, raw_weights, raw_end_at_step, alpha_blend, *cur_weight_sliders = args
    ValueError: not enough values to unpack (expected at least 6, got 0)

---

**Comment by a2569875** [comment]
很抱歉，我這邊重現不了你的錯誤。 從你輸出的錯誤訊息看來是你更新插件後沒有把webui終端機重開導致它讀到舊版的函數所導致。請嘗試重新安裝composable-lora 並且一定要記得把webui終端機重開 試試

**Comment by alphaply** [comment]
我尝试重新安装了sdwebui，问题应该解决了
