### ISSUE TITLE
RuntimeError: The size of tensor a (80) must match the size of tensor b (78) at non-singleton dimension 2

### ISSUE THREAD

**Issue by wikid24** [a2569875/stable-diffusion-webui-composable-lora#15]
Hi, 
I created a LORA (SD1.5, 512x512) using this guide with Kohya_SS : https://www.youtube.com/watch?v=70H03cv57-o
- JSON presets for Kohya_SS: [file: (LoraLowVRAMSettings.zip](https://github.com/a2569875/stable-diffusion-webui-composable-lora/files/11973047/LoraLowVRAMSettings.zip)
- My LORA file in question (153mb) : https://www.mediafire.com/file/5s3c8bigjekm4u5/Nala_Crafter%2528FFXIV-SD15A-100Steps%2529.zip/file

Environment:
- Windows 10
- Automatic 1111
- ControlNet  v1.1.230
- Latent Couple
- Composable LORA

I am running into error with:
ControlNet (OpenPose)  + Latent Couple + Composable LORA: **RuntimeError: The size of tensor a (80) must match the size of tensor b (78) at non-singleton dimension 2**

What works successfully:
- prompt w/ a CivitAI LORA +  Composable LORA enabled
- prompt w/ my own custom LORA  + Composable LORA disabled

What throws this error:
- prompt w/ my own custom LORA (see attachment above) +  Composable LORA enabled

I don't understand because it is SD1.5 512x512, which is the same as the other files from CivitAI... Is there a defect in Composable LORA or is it my custom LORA file?

I don't understand 

```
2023-07-06 15:38:26,634 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_openpose [cab727d4]
2023-07-06 15:38:26,637 - ControlNet - INFO - Loading preprocessor: openpose_full
2023-07-06 15:38:26,637 - ControlNet - INFO - preprocessor resolution = 512
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]Composable LoRA load successful.
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
*** Error completing request
*** Arguments: ('task(0bkirt7oy31u4d8)', "outdoors, wide angle\nAND 1girl, solo,  fighting stance, casting spell, angry, open mouth,  <lora:Y'shtola v3:1>, y'shtola_tpa, black long dress, facial mark,(fur-trimmed dress):1.3, whisker markings, bare shoulders, medium breasts,  choker,feather earrings, sexy\nAND 1boy, solo, fighting stance,  holding small knives, armor,armored boots, angry, open mouth    <lora:Nala_Crafter(FFXIV-SD15A-100Steps):1>", '(worst quality, low quality:1.4), deformed, chibi,', [], 20, 0, False, False, 1, 1, 7, 3775085251.0, -1.0, 0, 0, 0, False, 512, 768, True, 0.4, 2, 'R-ESRGAN 4x+ Anime6B', 15, 0, 0, 0, '', '', [], 0, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000016A40147220>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000016A47F18E50>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000016A36E85780>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000016A3754C2E0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000016A401A3AC0>, True, False, False, False, False, False, False, True, '1.00:1.00,1.00:2.25,1.00:1.80', '0.00:0.00,0.00:0.00,0.00:0.80', '0.2,0.8,0.8', 150, 0.2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "D:\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "D:\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\txt2img.py", line 57, in txt2img
        processed = processing.process_images(p)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 620, in process_images
        res = process_images_inner(p)
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 739, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 350, in process_sample
        return process.sample_before_CN_hack(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 992, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "D:\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 439, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "D:\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 278, in launch_sampling
        return func()
      File "D:\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 439, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 158, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "D:\stable-diffusion\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 661, in forward_webui
        return forward(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 580, in forward
        h = module(h, emb, context)
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 82, in forward
        x = layer(x, emb)
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 249, in forward
        return checkpoint(
      File "D:\stable-diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
        return CheckpointFunction.apply(func, len(inputs), *args)
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
        return super().apply(*args, **kwargs)  # type: ignore[misc]
      File "D:\stable-diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
        output_tensors = ctx.run_function(*ctx.input_tensors)
      File "D:\stable-diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 262, in _forward
        h = self.in_layers(x)
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
        input = module(input)
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-composable-lora\composable_lora.py", line 492, in lora_Conv2d_forward
        res = lora_forward(self, input, res)
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-composable-lora\composable_lora.py", line 77, in lora_forward
        res = apply_composable_lora(lora_layer_name, m_lora, module, "lora", patch, alpha, res, num_loras, num_prompts)
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-composable-lora\composable_lora.py", line 359, in apply_composable_lora
        res[tensor_off] = composable_lycoris.composable_forward(module, patch[tensor_off], alpha, multiplier, res[tensor_off])
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-composable-lora\composable_lycoris.py", line 67, in composable_forward
        return res + multiplier * alpha * patch
    RuntimeError: The size of tensor a (80) must match the size of tensor b (78) at non-singleton dimension 2
```

**Comment by wikid24** [comment]
Update: my custom LORA file used the LORA Type/Model "Kohya LoCon", which I believe is a part of the issue. I regenerated the same file with (mostly) the same parameters using the "Standard LoRA"  model instead and it seems the issue has gone away, BUT I am not 100% sure since I changed a bunch of different values.... Further testing is required.

**Comment by andupotorac** [comment]
On my end I get the same error:
RuntimeError: The size of tensor a (64) must match the size of tensor b (62) at non-singleton dimension 2

Is this extension not working anymore?
