### ISSUE TITLE
UnboundLocalError and AttributeError occured in latest upgrade

### ISSUE THREAD

**Issue by obs945** [a2569875/stable-diffusion-webui-composable-lora#17]
After upgrade to latest version composable-lora below error occured

====

Error running process: /Users/XXX/stable-diffusion-webui/extensions/stable-diffusion-webui-composable-lora/scripts/composable_lora_script.py
Traceback (most recent call last):
  File "/Users/XXX/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/Users/XXX/stable-diffusion-webui/extensions/stable-diffusion-webui-composable-lora/scripts/composable_lora_script.py", line 101, in process
    lora_ext.load_lora_ext()
  File "/Users/XXX/stable-diffusion-webui/extensions/stable-diffusion-webui-composable-lora/lora_ext.py", line 53, in load_lora_ext
    if hasattr(networks, "network_Linear_forward"):
UnboundLocalError: local variable 'networks' referenced before assignment

==== 

Error running process: /Users/XXX/stable-diffusion-webui/extensions/stable-diffusion-webui-composable-lora/scripts/composable_lora_script.py
Traceback (most recent call last):
  File "/Users/XXX/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/Users/XXX/stable-diffusion-webui/extensions/stable-diffusion-webui-composable-lora/scripts/composable_lora_script.py", line 101, in process
    lora_ext.load_lora_ext()
  File "/Users/XXX/stable-diffusion-webui/extensions/stable-diffusion-webui-composable-lora/lora_ext.py", line 53, in load_lora_ext
    if hasattr(networks, "network_Linear_forward"):
UnboundLocalError: local variable 'networks' referenced before assignment

====

Error running postprocess: /Users/XXX/stable-diffusion-webui/extensions/stable-diffusion-webui-composable-lora/scripts/composable_lora_script.py
Traceback (most recent call last):
  File "/Users/XXX/stable-diffusion-webui/modules/scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
  File "/Users/XXX/stable-diffusion-webui/extensions/stable-diffusion-webui-composable-lora/scripts/composable_lora_script.py", line 144, in postprocess
    composable_lora_function_handler.on_disable()
  File "/Users/XXX/stable-diffusion-webui/extensions/stable-diffusion-webui-composable-lora/composable_lora_function_handler.py", line 45, in on_disable
    torch.nn.Linear.forward = composable_lora.backup_lora_Linear_forward
AttributeError: module 'composable_lora' has no attribute 'backup_lora_Linear_forward'

**Comment by obs945** [comment]
My SD environment

python: 3.10.10
torch: 2.0.1
xformers: N/A
gradio: 3.32.0 
SD commit: [1e30ae89](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/1e30ae895e487b1b4b81033db14863c702d26268)
