### ISSUE TITLE
Error while using  Additional Networks with Composable LoRA disabled.

### ISSUE THREAD

**Issue by mbastias** [a2569875/stable-diffusion-webui-composable-lora#26]
I'm having an error even though the checkbox is on disabled at the Composable LoRA tab. Seems like a bad interaction with the Additional Networks extension, which I use a lot while making and testing LoRAs.
<details><summary>Error</summary>
<p>

```
    Traceback (most recent call last):
      File "C:\SD-GUI-1.4.0\webui\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "C:\SD-GUI-1.4.0\webui\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "C:\SD-GUI-1.4.0\webui\modules\txt2img.py", line 57, in txt2img
        processed = processing.process_images(p)
      File "C:\SD-GUI-1.4.0\webui\modules\processing.py", line 620, in process_images
        res = process_images_inner(p)
      File "C:\SD-GUI-1.4.0\webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "C:\SD-GUI-1.4.0\webui\modules\processing.py", line 729, in process_images_inner
        p.setup_conds()
      File "C:\SD-GUI-1.4.0\webui\modules\processing.py", line 1126, in setup_conds
        super().setup_conds()
      File "C:\SD-GUI-1.4.0\webui\modules\processing.py", line 346, in setup_conds
        self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, self.negative_prompts, self.steps * self.step_multiplier, [self.cached_uc], self.extra_network_data)
      File "C:\SD-GUI-1.4.0\webui\modules\processing.py", line 338, in get_conds_with_caching
        cache[1] = function(shared.sd_model, required_prompts, steps)
      File "C:\SD-GUI-1.4.0\webui\modules\prompt_parser.py", line 143, in get_learned_conditioning
        conds = model.get_learned_conditioning(texts)
      File "C:\SD-GUI-1.4.0\webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 669, in get_learned_conditioning
        c = self.cond_stage_model(c)
      File "C:\SD-GUI-1.4.0\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\SD-GUI-1.4.0\webui\modules\sd_hijack_clip.py", line 229, in forward
        z = self.process_tokens(tokens, multipliers)
      File "C:\SD-GUI-1.4.0\webui\modules\sd_hijack_clip.py", line 254, in process_tokens
        z = self.encode_with_transformers(tokens)
      File "C:\SD-GUI-1.4.0\webui\modules\sd_hijack_clip.py", line 302, in encode_with_transformers
        outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
      File "C:\SD-GUI-1.4.0\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\SD-GUI-1.4.0\system\python\lib\site-packages\transformers\models\clip\modeling_clip.py", line 811, in forward
        return self.text_model(
      File "C:\SD-GUI-1.4.0\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\SD-GUI-1.4.0\system\python\lib\site-packages\transformers\models\clip\modeling_clip.py", line 721, in forward
        encoder_outputs = self.encoder(
      File "C:\SD-GUI-1.4.0\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\SD-GUI-1.4.0\system\python\lib\site-packages\transformers\models\clip\modeling_clip.py", line 650, in forward
        layer_outputs = encoder_layer(
      File "C:\SD-GUI-1.4.0\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\SD-GUI-1.4.0\system\python\lib\site-packages\transformers\models\clip\modeling_clip.py", line 379, in forward
        hidden_states, attn_weights = self.self_attn(
      File "C:\SD-GUI-1.4.0\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\SD-GUI-1.4.0\system\python\lib\site-packages\transformers\models\clip\modeling_clip.py", line 268, in forward
        query_states = self.q_proj(hidden_states) * self.scale
      File "C:\SD-GUI-1.4.0\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\SD-GUI-1.4.0\webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 91, in forward
        return self.org_forward(x) + self.lora_up(self.lora_down(x)) * self.multiplier * self.scale
      File "C:\SD-GUI-1.4.0\webui\extensions\stable-diffusion-webui-composable-lora\composable_lora.py", line 451, in lora_Linear_forward
        return lycoris.lyco_Linear_forward(self, input)
      File "C:\SD-GUI-1.4.0\webui\extensions\a1111-sd-webui-lycoris\lycoris.py", line 741, in lyco_Linear_forward
        return torch.nn.Linear_forward_before_lyco(self, input)
    TypeError: 'NoneType' object is not callable
``` 

</p>
</details> 

I had to disable Composable LoRA from the Extensions tab for Additional Networks to work again.

**Comment by FriedGenera** [comment]
Did you ever figure out a solution to this?

**Comment by SenshiSentou** [comment]
+1 Same here on MacOS. Attempting to use any LoRA hard-crashes A1111. `./webui.sh: line 255: 41577 Segmentation fault: 11  "${python_cmd}" -u "${LAUNCH_SCRIPT}" "$@"`
