### ISSUE TITLE
AttributeError: module 'composable_lora' has no attribute 'should_reload'

### ISSUE THREAD

**Issue by CaptnSeraph** [a2569875/stable-diffusion-webui-composable-lora#3]
Error running process: I:\stable-diffusion-webui\extensions\stable-diffusion-webui-composable-lora\scripts\composable_lora_script.py
Traceback (most recent call last):
  File "I:\stable-diffusion-webui\modules\scripts.py", line 418, in process
    script.process(p, *script_args)
  File "I:\stable-diffusion-webui\extensions\stable-diffusion-webui-composable-lora\scripts\composable_lora_script.py", line 71, in process
    composable_lora_function_handler.on_enable()
  File "I:\stable-diffusion-webui\extensions\stable-diffusion-webui-composable-lora\composable_lora_function_handler.py", line 35, in on_enable
    if (composable_lora.should_reload() or (torch.nn.Linear.forward != composable_lora.lora_Linear_forward)):
AttributeError: module 'composable_lora' has no attribute 'should_reload'

**Comment by a2569875** [comment]
@CaptnSeraph did you uninstall old composable-lora before install this version of composable-lora?

**Comment by CaptnSeraph** [comment]
I did, but maybe I didn't unload reload everything. I'll try cleaning up and doing it properly

**Comment by a2569875** [comment]
> I did, but maybe I didn't unload reload everything. I'll try cleaning up and doing it properly

Is the problem solved after restarting the webui? @CaptnSeraph

**Comment by CaptnSeraph** [comment]
Yep.
